# Generated by Django 5.1 on 2024-09-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='colores',
            field=models.CharField(choices=[('AM', 'AMARILLO'), ('AZ', 'AZUL'), ('RO', 'ROJO')], default='Gris', max_length=2),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(max_length=300),
        ),
    ]
